-- Census / Registry — Postgres schema for Supabase.
--
-- CANONICAL (GitHub Actions + CLI): supabase/migrations/20250101000000_bootstrap_schema.sql
-- Aplicar todo: npx supabase link && npx supabase db push
-- O pegar en SQL Editor el contenido de esa migración (proyectos sin CI).
--
-- NUEVOS CAMBIOS: npm run db:migration:new -- nombre  →  merge a main.
-- Ver AGENTS.md → SQL migrations.
